### ISSUE TITLE
Unexpected Result

### ISSUE THREAD

**Issue by shakna-israel** [Drahflow/Elymas#5]
It might be that I'm doing something insane, but glancing over Elymas, and seeing it was sorta list based, I gave a command a shot and got something I really didn't expect:

```
5 2 3 6 add dump
0000000000000009
```

I kind of expected either:

```
0000000000000007
```

Where Elymas ignored the extra items, or

```
0000000000000016
```

if actually performed like a list.

As it is, I'm not sure what value is being returned or why.

**Comment by lutoma** [comment]
So I'm by no means an expert on the language, but from my limited understanding, this is happening:

You're adding 5, 2, 3 and 6 to the stack. Add operates on the last two items on the stack – which at the time you call it are 3 and 6. So the result is 9.

To get 16 you'd have to do `5 2 add 3 add 6 add dump` (There's probably a more elegant way I'm not aware of).

Please correct me if I'm wrong, @Drahflow.

**Comment by shakna-israel** [comment]
... That makes perfect sense.
