### ISSUE TITLE
Build fails on Ubuntu

### ISSUE THREAD

**Issue by Drahflow** [Drahflow/Elymas#7]
... initially reported in #2, specifically https://github.com/Drahflow/Elymas/issues/2#issuecomment-293856864.

**Comment by danieltanfh95** [comment]
I replicated this on 
```
No LSB modules are available.
Distributor ID:	elementary
Description:	elementary OS 0.4 Loki
Release:	0.4
Codename:	loki
```

and it ran fine. 

At this point I think it's because I tried it on WSL instead, so some system calls have not been implemented on their side. You can close this issue.

**Comment by Drahflow** [comment]
I added travis builds now, which are also based on Ubuntu.
